# netlify.toml

[build]
  functions = "netlify/functions"
  # publish = "." # Your publish directory

# Optional: redirect for cleaner API calls from the client
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# General functions settings (apply to all functions unless overridden)
[functions]
  directory = "netlify/functions" # This is usually redundant if [build].functions is set, but harmless
  # node_bundler = "esbuild" # You can keep or remove this, it's a bundler choice
  # included_files = ["!node_modules/crypto-js/**", "!node_modules/node-fetch/**"] # If you added this

# Specific configuration for the 'get-binance-trades' function
[functions.get-binance-trades] # Single square brackets for a specific function config
  region = "eu-central-1"
  # You can add other per-function settings here if needed, like:
  # memory = 256
  # timeout = 20